name: Publish Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-publish-pip-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            - ${{ runner.os }}-publish-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - name: Build package
        run: |
          python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
