name: test

on:
  push:
    branches:
      - main
      - "test-me-*"

  pull_request:
    branches:
      - "*"


# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build and Check Package
        uses: hynek/build-and-inspect-python-package@v2.14

  test:
    needs: [package]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5

    - name: Download Package
      uses: actions/download-artifact@v5
      with:
        name: Packages
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Test
      shell: bash
      run: |
        tox run -e py --installpkg `find dist/*.tar.gz`
